-- Migration 010: RAG Knowledge Base — 10+ documents
-- Comprehensive startup knowledge for the AI agent

-- Check existing chunks count (we add if not enough)
-- Each document is chunked into 2-6 segments for better retrieval

-- ===== 1. Lean Startup =====
INSERT INTO knowledge_chunks (document_title, document_source, content, chunk_index, metadata) VALUES
('Lean Startup — Методология', 'lean-startup', 'Lean Startup — это подход к созданию бизнеса, разработанный Эриком Рисом. Ключевые принципы: 1) Build-Measure-Learn (Создай-Измерь-Учись) — главный цикл обратной связи. Вместо длительного планирования, создайте MVP и тестируйте. 2) Validated Learning — единственная метрика прогресса это подтверждённое обучение через эксперименты с реальными клиентами. 3) Pivot or Persevere — регулярно принимайте решение: продолжать текущий курс или совершить пивот (фундаментальное изменение стратегии).', 0, '{"topic": "methodology", "stage": "all"}'),
('Lean Startup — MVP', 'lean-startup', 'MVP (Minimum Viable Product) — минимальный жизнеспособный продукт. Это версия продукта с минимальным набором функций, достаточным для проверки гипотезы. Типы MVP: 1) Wizard of Oz — ручное выполнение за фасадом автоматизации. 2) Concierge MVP — персональное обслуживание вместо масштабного решения. 3) Landing page MVP — страница с описанием продукта для проверки спроса. 4) Video MVP (Dropbox) — видеодемонстрация концепции до реализации. Главное правило: MVP должен проверять одну конкретную гипотезу.', 1, '{"topic": "mvp", "stage": "mvp"}'),
('Lean Startup — Метрики', 'lean-startup', 'Метрики для стартапа должны быть actionable (побуждающие к действию), accessible (понятные), auditable (проверяемые). Избегайте vanity metrics (тщеславных метрик): лайки, просмотры страниц, количество регистраций без активации. Фокусируйтесь на: Activation rate, Retention rate, Revenue per user, NPS. Для SaaS: MRR, ARR, Churn rate, LTV/CAC ratio. Когортный анализ — лучший способ отслеживать прогресс. Распределяйте пользователей по когортам (неделя/месяц регистрации) и смотрите Retention.', 2, '{"topic": "metrics", "stage": "mvp"}');

-- ===== 2. Customer Development (CustDev) =====
INSERT INTO knowledge_chunks (document_title, document_source, content, chunk_index, metadata) VALUES
('Customer Development — Основы', 'custdev', 'Customer Development (CustDev) по Стиву Бланку — процесс поиска и валидации бизнес-модели. 4 этапа: 1) Customer Discovery — поиск проблемы и клиента. 2) Customer Validation — проверка решения и каналов. 3) Customer Creation — масштабирование. 4) Company Building — построение организации. На этапе Discovery: выходите из офиса, разговаривайте с 50+ потенциальными клиентами, задавайте открытые вопросы. Никогда не спрашивайте «Вы бы купили наш продукт?» — спрашивайте о проблемах.', 0, '{"topic": "custdev", "stage": "validation"}'),
('Customer Development — Интервью', 'custdev', 'Правила CustDev-интервью (по книге «The Mom Test»): 1) Не спрашивайте о будущем — люди плохо предсказывают своё поведение. 2) Спрашивайте о прошлом опыте: «Расскажите, как вы в последний раз столкнулись с...?» 3) Не продавайте во время интервью. 4) Не ведите за собой — позвольте собеседнику говорить. 5) Ищите конкретику: «Сколько это вам стоило?», «Как часто это происходит?». Хороший вопрос: «Как вы сейчас решаете эту проблему?» Плохой: «Вам нравится идея приложения, которое...?»', 1, '{"topic": "custdev", "stage": "validation"}');

-- ===== 3. Business Model Canvas (BMC) =====
INSERT INTO knowledge_chunks (document_title, document_source, content, chunk_index, metadata) VALUES
('BMC — Методология', 'bmc', 'Business Model Canvas (Остервальдер, Пинье) — визуальный инструмент описания бизнес-модели из 9 блоков: 1) Customer Segments — для кого создаём ценность? Типы сегментов: Mass market, Niche, Segmented, Multi-sided. 2) Value Propositions — какую ценность предлагаем? Newness, Performance, Customization, Getting the job done, Design, Brand/Status, Price, Cost reduction. 3) Channels — как доставляем ценность? Awareness → Evaluation → Purchase → Delivery → After Sales. 4) Customer Relationships — тип отношений: Personal, Self-service, Automated, Communities.', 0, '{"topic": "bmc", "stage": "business_model"}'),
('BMC — Финансовые блоки', 'bmc', 'BMC продолжение: 5) Revenue Streams — за что платят? Модели: продажа актива, подписка, лицензия, реклама, freemium, marketplace комиссия. 6) Key Resources — физические, интеллектуальные, человеческие, финансовые. 7) Key Activities — производство, решение проблем, платформа/сеть. 8) Key Partnerships — стратегические альянсы, joint ventures, поставщики. 9) Cost Structure — фиксированные / переменные затраты, экономия масштаба. Совет: заполняйте BMC итеративно, начиная с Value Proposition и Customer Segments.', 1, '{"topic": "bmc", "stage": "business_model"}');

-- ===== 4. Value Proposition Canvas =====
INSERT INTO knowledge_chunks (document_title, document_source, content, chunk_index, metadata) VALUES
('VPC — Ценностное предложение', 'vpc', 'Value Proposition Canvas (VPC) — инструмент детального анализа соответствия продукта потребностям клиента. Сторона клиента: 1) Jobs — функциональные (что делает?), социальные (как выглядит?), эмоциональные (как себя чувствует?) задачи. 2) Pains — нежелательные результаты, препятствия, риски. 3) Gains — ожидаемые выгоды, желаемые результаты, неожиданные бонусы. Сторона ценности: 1) Products & Services — что предлагаем. 2) Pain Relievers — как снимаем боли. 3) Gain Creators — как создаём выгоды. Цель: Product-Market Fit = Pain Relievers покрывают Pains + Gain Creators усиливают Gains.', 0, '{"topic": "vpc", "stage": "business_model"}');

-- ===== 5. Юнит-экономика =====
INSERT INTO knowledge_chunks (document_title, document_source, content, chunk_index, metadata) VALUES
('Юнит-экономика — Основы', 'unit-economics', 'Юнит-экономика — анализ прибыльности одной единицы бизнеса (пользователь/транзакция). Ключевые метрики: CAC (Customer Acquisition Cost) = маркетинг / новые клиенты. LTV (Lifetime Value) = ARPU / Churn. Правило: LTV/CAC ≥ 3 для здорового бизнеса. Payback Period = CAC / ARPU (месяцы до возврата). ARPU = выручка / активные пользователи. Churn rate = ушедшие / всего (помесячно). Unit Economics позитивна, когда LTV > CAC. Для SaaS: MRR (Monthly Recurring Revenue), ARR, Net Revenue Retention.', 0, '{"topic": "unit_economics", "stage": "business_model"}'),
('Юнит-экономика — Улучшение', 'unit-economics', 'Как улучшить юнит-экономику: Снижение CAC: 1) Органические каналы (SEO, контент, вирусность). 2) Реферальные программы. 3) Улучшение конверсии воронки. 4) Таргетинг на правильную аудиторию. Увеличение LTV: 1) Повышение Retention (onboarding, engagement). 2) Upsell/Cross-sell. 3) Увеличение ARPU (тарифные планы, премиум-функции). 4) Снижение churn (customer success, обратная связь). Бенчмарки SaaS B2B: CAC Payback < 18 мес, Logo Churn < 5%/год, Net Dollar Retention > 110%, LTV/CAC > 3x. Для B2C: CAC < LTV/3, Day-30 Retention > 20%.', 1, '{"topic": "unit_economics", "stage": "business_model"}');

-- ===== 6. Питч-дек =====
INSERT INTO knowledge_chunks (document_title, document_source, content, chunk_index, metadata) VALUES
('Питч-дек — Структура', 'pitch-deck', 'Структура питч-дека (10 слайдов): 1) Обложка — название, логотип, слоган. 2) Проблема — боль клиента (данные, история). 3) Решение — ваш продукт, скриншоты, демо. 4) Рынок — TAM (общий), SAM (доступный), SOM (целевой). 5) Продукт — MVP, технология, USP. 6) Бизнес-модель — как зарабатываете, юнит-экономика. 7) Конкуренты — матрица сравнения (NOT «у нас нет конкурентов»). 8) Traction — метрики, пользователи, выручка, рост. 9) Команда — кто стоит за проектом, экспертиза. 10) Roadmap и Ask — план действий и запрос (инвестиции, менторство).', 0, '{"topic": "pitch", "stage": "pitch"}'),
('Питч-дек — Советы', 'pitch-deck', 'Советы для питча: 1) Правило 10-20-30 (Guy Kawasaki): 10 слайдов, 20 минут, шрифт ≥ 30pt. 2) Storytelling — начните с истории конкретного клиента. 3) Числа > слова: «500 активных пользователей, рост 20% M-o-M» лучше «много пользователей». 4) Конкуренты: признайте их, покажите своё отличие. 5) Команда: сфокусируйтесь на релевантном опыте. 6) Ask: будьте конкретны — «Мы ищем 5 млн ₽ на 12 месяцев для достижения PMF». 7) Worst case: подготовьте ответы на каверзные вопросы. Типичные вопросы инвестора: «Почему именно вы?», «Что если Google сделает это?», «Какой burn rate?».', 1, '{"topic": "pitch", "stage": "pitch"}');

-- ===== 7. JTBD (Jobs To Be Done) =====
INSERT INTO knowledge_chunks (document_title, document_source, content, chunk_index, metadata) VALUES
('JTBD — Теория', 'jtbd', 'Jobs To Be Done (JTBD) — теория, фокусирующаяся на «работе», которую клиент «нанимает» продукт выполнить. Формула: «Когда [ситуация], я хочу [мотивация], чтобы [ожидаемый результат]». Пример: «Когда я еду на работу утром, я хочу быстро перекусить, чтобы не быть голодным до обеда» — это Job-to-be-done, конкурирующий с Snickers, бананом и протеиновым батончиком. Типы jobs: Functional (функциональные), Emotional (эмоциональные), Social (социальные). Для CustDev: ищите Switch Moments — моменты, когда клиент переключается с одного решения на другое.', 0, '{"topic": "jtbd", "stage": "validation"}');

-- ===== 8. Product-Market Fit =====
INSERT INTO knowledge_chunks (document_title, document_source, content, chunk_index, metadata) VALUES
('Product-Market Fit — Признаки', 'pmf', 'Product-Market Fit (PMF) — состояние, когда продукт удовлетворяет реальный рыночный спрос. Признаки PMF (Marc Andreessen): «Вы чувствуете PMF, когда он наступает — продукт разлетается быстрее, чем вы успеваете обслужить». Количественные индикаторы: 1) Sean Ellis Test — ≥40% пользователей «были бы очень разочарованы» потеряв продукт. 2) NPS > 50. 3) Органический рост > 50% от общего. 4) DAU/MAU > 25% (для consumer), > 50% (для SaaS). До PMF: фокус на поиске (CustDev, пивоты). После PMF: фокус на масштабировании (growth, unit economics).', 0, '{"topic": "pmf", "stage": "mvp"}');

-- ===== 9. Формирование команды =====
INSERT INTO knowledge_chunks (document_title, document_source, content, chunk_index, metadata) VALUES
('Стартап-команда — Роли', 'team', 'Идеальная команда стартапа (модель H3): Hustler (бизнес) — продажи, партнёрства, fundraising. Hacker (технология) — разработка продукта, архитектура. Hipster (дизайн) — UX, визуал, бренд. Не обязательно три человека — один может совмещать роли. Ключевые качества: 1) Complementary skills — навыки дополняют друг друга. 2) Shared vision — общее видение. 3) Resilience — устойчивость к неудачам. 4) Speed — скорость принятия решений. Красные флаги: все кофаундеры с одинаковым бэкграундом, нет технического сооснователя, равный split без вестинга. Рекомендация: 4-year vesting с 1-year cliff.', 0, '{"topic": "team", "stage": "idea"}');

-- ===== 10. Воронка и Growth =====
INSERT INTO knowledge_chunks (document_title, document_source, content, chunk_index, metadata) VALUES
('Growth — Воронка AARRR', 'growth', 'Пиратские метрики (AARRR, Dave McClure): 1) Acquisition — откуда приходят пользователи? Каналы: SEO, SEM, SMM, контент, вирусность, партнёрства. 2) Activation — первый WOW-момент. Метрика: % завершивших onboarding. 3) Retention — возвращаются ли? Day-1, Day-7, Day-30 Retention. Самая важная метрика. 4) Revenue — платят ли? Conversion rate, ARPU, MRR. 5) Referral — рекомендуют ли? К-коэффициент вирусности = приглашения × конверсия. Growth Hacking: фокус на одном «рычаге» за раз. North Star Metric — единая метрика, отражающая ценность для пользователя.', 0, '{"topic": "growth", "stage": "mvp"}'),
('Growth — Каналы привлечения', 'growth', 'Каналы привлечения (Traction Channels по Вайнбергу/Мэрсу): 19 каналов — протестируйте 3-5, выберите 1-2. Категории: 1) Платные: таргетированная реклама (VK, Telegram), контекстная реклама (Яндекс.Директ). 2) Органические: SEO, контент-маркетинг, SMM, community building. 3) Партнёрские: кросс-промо, affiliate, интеграции. 4) Вирусные: реферальные программы, продуктовая вирусность. Для России актуально: Telegram-каналы, VK, партнёрства с акселераторами (ФРИИ, Сколково, ВШЭ). Для B2B: LinkedIn, конференции, direct sales. Методика Bullseye: среднее кольцо (перспективные) → внутреннее кольцо (тестируемые) → центр (работающие).', 1, '{"topic": "growth", "stage": "mvp"}');

-- ===== 11. Анализ конкурентов =====
INSERT INTO knowledge_chunks (document_title, document_source, content, chunk_index, metadata) VALUES
('Конкурентный анализ', 'competitors', 'Анализ конкурентов для стартапа: 1) Прямые конкуренты — решают ту же проблему тем же способом. 2) Косвенные — решают ту же проблему другим способом. 3) Потенциальные — могут войти на рынок (крупные игроки). Инструменты: Competitive Matrix (таблица сравнения по фичам). Positioning Map (2 оси: цена vs качество). Не говорите «у нас нет конкурентов» — конкурент №1 это «ничего не делать» (status quo). Вместо этого: «Вот как мы отличаемся от X, Y, Z по ключевым параметрам». Sustainable Competitive Advantage: сетевые эффекты, данные, IP, экосистема, бренд, switching costs.', 0, '{"topic": "competitors", "stage": "validation"}');

-- ===== 12. Финансовое планирование =====
INSERT INTO knowledge_chunks (document_title, document_source, content, chunk_index, metadata) VALUES
('Финансы стартапа — Основы', 'finance', 'Финансовое планирование стартапа: 1) Runway = доступные средства / monthly burn rate. Нужен минимум 12-18 месяцев runway. 2) Burn Rate — сколько тратите в месяц. Gross burn (все расходы) vs Net burn (расходы минус доходы). 3) Раунды: Pre-seed (0.5-3 млн ₽, идея + прототип), Seed (3-30 млн ₽, PMF), Series A (30-300 млн ₽, масштабирование). 4) Dilution — при каждом раунде основатели отдают 15-25% компании. 5) Valuation: Pre-money (до инвестиций) + Investment = Post-money. Правило: не привлекайте деньги, пока не знаете, зачем они вам. Каждый рубль должен приближать к следующему milestone.', 0, '{"topic": "finance", "stage": "pitch"}');
